### ISSUE TITLE
Data is not refreshed

### ISSUE THREAD

**Issue by WillyW72** [bajansen/home-assistant-frank_energie#102]
Hello,

Yesterday I installed the Frank Energie integration. It works fine, but it seems that the data is not being refreshed. I now see the price information until the end of the day and not yet the beginning of tomorrow.

![image](https://github.com/bajansen/home-assistant-frank_energie/assets/132304948/9d740c6e-602d-47f1-90bb-8bd87669b544)

When the integration is reloaded, tomorrow's price information will become visible.
Do I need to set anything to update this price information automatically?

Regards, Wilfred

**Comment by DCSBL** [comment]
This has to do with some instabilities from the Frank Energie API. We can make logic so the API refreshes more often when this happens, but for now this is what it is.
