### ISSUE TITLE
today prijzen neemt volgende dag mee.

### ISSUE THREAD

**Issue by Tazzios** [bajansen/home-assistant-frank_energie#11]
Na 15:00 zijn de prijzen van morgen bekend
de entiteiten low,avarage, high today nemen deze waarde mee bij hun berekening.

**Comment by bajansen** [comment]
Het is misschien vooral verwarrend dat de sensoren 'today' in de naam hebben. Het was namelijk wel mijn bedoeling ook de informatie van de komende dag mee te nemen zodat je in een automatisering zou kunnen kijken of de huidige prijs onder het gemiddelde ligt en om dan een apparaat in te schakelen. Als je dan richting het einde van de dag een vaatwasser aan zou willen zetten is het wel zinvol om naar de prijzen van in ieder geval de volgende ochtend te kijken.

Ik moet zeggen dat ik zelf niets doe met de waarden van deze sensoren, maar aangezien een aanpassing hierin het verwachte gedrag van automatiseringen nogal kan veranderen laat ik dit even openstaan voor suggesties van anderen of tot ik zelf een geniale ingeving heb.

**Comment by Tazzios** [comment]
Geen probleem zo is het in ieder geval bekend. :)

Wat betreft oplossing een grafiekweergave is denk toch het handigst. Indien ik zie wat de low/high prijs is weet ik nog steeds niet welk uur dat is. (het uur bij de high and low meegeven zou ook een oplossing kunnen zijn maar dat is minder visueel aantrekkelijk) 

Het is mij onduidelijk of het getoonde voorbeeld in #2 al bruikbaar is/ beschikbaar is om een grafiek van te maken.

**Comment by sfstar** [comment]
Het zou misschien fijn zijn als er een aparte upcoming  entity komt die na het verstrijken van een uur de waarde van het vorige uur niet meer laat zien.
Waarbij de average price, low en high (in een aparte upcoming vorm) ervoor kunnen zorgen dan mensen beter kunnen automatiseren op toekomstige prijzen.
Aangezien de huidige average, low en high ook nog prijzen meenemen die al niet meer van toepassing zijn.
Waardoor deze misleidend kunnen zijn / moeilijk te gebruiken bij automatisering.

**Comment by HiDiHo01** [comment]
Goeie tip, komt eraan.
Ik heb het klaar alleen nog even testen.

Op ma 17 okt. 2022 18:22 schreef sfstar ***@***.***>:
