### ISSUE TITLE
Verschil in prijzen bij inloggen en niet inloggen

### ISSUE THREAD

**Issue by HiDiHo01** [bajansen/home-assistant-frank_energie#113]
Dit is niet zozeer een Issue van deze integratie maar van Frank Energie zelf

De Gemiddelde elektriciteitsprijs vandaag (All-in) verschilt bij de ingelogde prijzen en niet ingelogde prijzen
De inkoopvergoeding (markup) is hoger als je inlogt (dus ook de all-in prijs)
Op de hun site staat nu bv € 0,259 /kWh Gem stroomprijs en in de android app € 0,266 /kWh

Hebben meer mensen dit? En waarom verschilt het?

**Comment by HiDiHo01** [comment]
Hoe toevallig....gisteravond om 23:30uur is mijn inkoopvergoeding verlaagt van 0,02541 naar 0.01815
Nu zijn de openbare en abonnee prijzen weer gelijk.

**Comment by RonVoormeeren** [comment]
Ik heb het verschil ook, https://eerlijkverbruik.nl/energie/frank-energie hier zie ik bijvoorbeeld dezelfde tarieven as in de app. De tarieven momenteel in Home Assistant zijn veel lager.

**Comment by HiDiHo01** [comment]
Ik denk dat de abonnement kosten erbij opgeteld zijn.

Op ma 23 sep 2024 10:33 schreef Ron ***@***.***>:
