### ISSUE TITLE
Add sensors for individual API fields

### ISSUE THREAD

**Issue by cascer1** [bajansen/home-assistant-frank_energie#16]
Hi,

I would appreciate it if the integration exposed sensors for all the individual APi fields (`marketPrice`, `marketPriceTax`, `sourcingMarkupPrice`, `energyTaxPrice`).  This is useful for me because I export my hourly energy data to a csv and need those values to accurately calculate the monthly energy cost. 

The reason that I want to do this is because the utility company (Enexis) suddenly stopped reading out my meter data and I want to keep track of how much more I'm paying due to their error.

Cheers

**Comment by bajansen** [comment]
Deze waarden werden al binnengehaald, ze zijn sinds b89ee3a ook beschikbaar als aparte sensoren. Omdat ze niet bijzonder veel informatie toevoegen voor de gemiddelde gebruiker staan ze standaard uitgeschakeld en dien je de betreffende sensorentiteiten dus wel handmatig in te schakelen voor je er data mee kunt loggen.
