### ISSUE TITLE
Gemiddelde prijs teruglevering kWh

### ISSUE THREAD

**Issue by edeba** [bajansen/home-assistant-frank_energie#21]
Hallo,

Een mooie integratie is deze Frank Energie dienst binnen Home Assistant. Ik vraag mij af of er ook een entiteit is die de gemiddelde prijs in kwH weergeeft voor de teruglevering (saldering) van energie?

Fijne dag, Eric

**Comment by bajansen** [comment]
Voor zover ik het begrijp krijg je bij teruglevering gewoon de actuele marktprijs vergoed en worden daarnaast de heffingen weggestreept voor alle afgenomen kWh <= de teruggeleverde kWh. Je kunt dus gewoon de huidige-prijsentiteit gebruiken voor het teruglevertarief, maar om op jaarbasis op de daadwerkelijke kosten uit te komen zul je ook het verschil tussen de afgenomen en teruggeleverde energie moeten bijhouden om de saldering te berekenen. Deze integratie biedt alleen de prijsgegevens zelf.

**Comment by edeba** [comment]
In de app laat hij wel 2 verschillende prijzen zien;

![01D613AC-6557-4541-A634-1FC0EA7AFAB7](https://user-images.githubusercontent.com/113854319/193345617-920c0ee1-18e0-49b0-9103-0433b20f55e4.jpeg)

**Comment by bajansen** [comment]
In de app wordt, zoals in het getoonde screenshot, ook gebruik gemaakt van gegevens die accountgebonden zijn. Deze integratie maakt alleen gebruik van de publieke API met openbare data en kan dergelijke gegevens dus niet zomaar inzichtelijk maken.

**Comment by jopvanraaij** [comment]
Klopt. Om een idee te geven, heb ik een screenshot van mijn gemiddeld verbruik toegevoegd. Als je je verbruik verplaatst naar tijden waarom de stroomprijs lager is, zul je een lager gemiddelde stroomprijs betalen. 
![Screenshot_20221002-102335](https://user-images.githubusercontent.com/2052634/193445134-56c16621-d25e-45c5-8790-242f3e594d7b.jpg)

In de faq van frankenergie zie je de exacte berekening van teruglevering. Dat is op basis van dezelfde prijs als voor verbruik (met wat extra constanten), zie https://cdn.sanity.io/files/8navd656/production/33a9f421ece752fb1cd28d500d8da3c6a2ca43c8.pdf?dl
