### ISSUE TITLE
Boolean sensor when actual price is lower than average

### ISSUE THREAD

**Issue by dikkiediknijland** [bajansen/home-assistant-frank_energie#25]
Hi,
I love your implementation and thanks for creating that! 
Question, is it possible to have a boolean sensor entity that is 'on' when the actual price is lower than the average and 'off' when the price is equal or higher than the average price.
Makes it easier for me check whether to enable an output, based on the relative energy price in a schedule.

**Comment by bajansen** [comment]
Je kunt zo'n vergelijking rechtstreeks als voorwaarde of trigger instellen in een automatisering met een waardesjabloon als dit:
`{{ states('sensor.current_electricity_price_all_in') < states('sensor.average_electricity_price_today') }}`

Wanneer je dit in meerdere automatiseringen wilt gebruiken kan het handig zijn een [_template binary sensor_](https://www.home-assistant.io/integrations/template/#configuration-variables) te maken met het genoemde sjabloon zodat je dan die sensor als trigger/voorwaarde kunt gebruiken en niet de hele tijd het sjabloon heen en weer hoeft te kopiëren.

**Comment by dikkiediknijland** [comment]
Ah nog beter, top ga ik proberen.
Dank je wel
