### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by HiDiHo01** [bajansen/home-assistant-frank_energie#30]
De api geeft geen data meer, misschien door het uur verschil (wintertijd)
correctie: er is wel data alleen niet van elektra vandaag/morgen, gas geeft wel voor 2 dagen data
De site Frank Energie en mobiele app geven ook niets meer aan.

Alle sensoren geven deze melding:
Deze entiteit is niet meer beschikbaar vanuit de frank_energie integratie. Wanneer de entiteit niet meer in gebruik is, kan deze vanuit de instellingen verwijderd worden.

**Comment by jopvanraaij** [comment]
Volgens mij ligt het aan Frankenergie: op de website en de app zijn ook geen energieprijzen zichtbaar. Neem aan dat ze hard aan het werk zijn om het op te lossen bij Frank...

**Comment by HiDiHo01** [comment]
> Volgens mij ligt het aan Frankenergie: op de website en de app zijn ook geen energieprijzen zichtbaar. Neem aan dat ze hard aan het werk zijn om het op te lossen bij Frank...

Ja klopt. Ik weet alleen niet hoe Home Assistant hier nu mee om gaat...zal wel opnieuw opstarten worden als er weer gegevens zijn

**Comment by bajansen** [comment]
De api werkt ondertussen weer. De prijsentiteiten stonden in mijn installatie nog op onbeschikbaar, na een herstart werkte het weer naar behoren. Het kan zijn dat dit komt doordat de informatie nog pas net beschikbaar is en dat de integratie deze data nog niet had opgehaald, of er blijft iets hangen waardoor een herstart nodig is.

**Comment by jopvanraaij** [comment]
Bij mij is het automatisch hersteld. Wel een gat in de history nu.
![Screenshot_20221030-163201](https://user-images.githubusercontent.com/2052634/198887450-96f86498-936b-4cb6-83f6-ba3a58f80cf8.jpg)

**Comment by HiDiHo01** [comment]
Bij mij bleef hij op de laatste prijs staan in de statistieken, sensor zelf gaf unavailable aan omdat ik overal de default "unavailable" ingesteld heb. Het vreende is dat prijzen voor "upcoming" en "morgen" wel automagisch terug kwam.
Het aantal uur geladen staat nu ook op 73 dus misschien moet ik nog iets aanpassen omdat ik nu delen door "24" uur ingesteld had.

<img src="https://i.gyazo.com/caf992e7a11e8a9db72e2fc9de5aaee7.png">

**Comment by HiDiHo01** [comment]
> De api werkt ondertussen weer. De prijsentiteiten stonden in mijn installatie nog op onbeschikbaar, na een herstart werkte het weer naar behoren. Het kan zijn dat dit komt doordat de informatie nog pas net beschikbaar is en dat de integratie deze data nog niet had opgehaald, of er blijft iets hangen waardoor een herstart nodig is.

Mijn ervaring is dat als de component een fout geeft er een herstart nodig is.
Als je "unavailable" terug laat komen als waarde voor de sensor gaat het meestal wel goed (dit doe ik voor sensors "morgen" omdat er na 0:00 uur geen data voor morgen aanwezig is. Om 15 uur komt dan vanzelf de nieuwe data in de sensors, zonder fout in het component)

**Comment by HiDiHo01** [comment]
Ik heb het volgende toegevoegd om een fout in het component te voorkomen
Dit werkt alleen als je 72 uur inlaadt, laadt je 48 uur in moet len(hourprices) == 0 zijn.

```
        if len(hourprices) == 24: #fix for when no data for today is available
            return 'unavailable'

```

**Comment by HiDiHo01** [comment]
Even wat wijzigingen doorgevoerd, alles werkt weer prima
extrahour_prices toegevoegd voor 1 dag per jaar....wanneer dag een extra uur heeft
(dit zal over een half jaar wel weer een probleem vormen maar dat pas ik dan wel aan)
Gemiddelde van vandaag klopt weer.

<img src="https://i.gyazo.com/d11bb215d3b63a9f0cd573345a27a2cc.png">

**Comment by HiDiHo01** [comment]
En weer zijn er geen gegevens...
Als Frank het zo slecht doet, begin ik echt te twijfelen of de rekening wel klopt

**Comment by HiDiHo01** [comment]
Hij werkt weer.

**Comment by HiDiHo01** [comment]
En weer geen gegevens

**Comment by bajansen** [comment]
Ik had nog geen tijd gehad om te kijken wat er gebeurde en dacht dat er bij Frank Energie gewoon iets hobbelde als gevolg van de wintertijd, maar het lijkt erop dat de API alleen nog maar data voor een enkele dag terug wil geven. Ik zal eens kijken of ik iets kan ombouwen.

**Comment by HiDiHo01** [comment]
Dit gaat een goedkoop maandje worden zo :P
<img src"https://i.gyazo.com/df4fbd629a7fc9b61f20b59a38663798.png">

**Comment by HiDiHo01** [comment]
Ik hoop wel dat prijzen voor morgen nog terugkomen

**Comment by bajansen** [comment]
Data van de volgende dag wordt nu weer opgehaald, als het goed is ook zonder stuk te gaan wanneer de data er niet is.
