### ISSUE TITLE
Opnieuw proberen in te stellen: can only concatenate list (not "NoneType") to list

### ISSUE THREAD

**Issue by tvdh91** [bajansen/home-assistant-frank_energie#31]
Ik krijg na het installeren volgens de handleiding deze melding te zien bij het pakket.
Na opnieuw installeren is het niet opgelost:

Opnieuw proberen in te stellen: can only concatenate list (not "NoneType") to list

**Comment by HiDiHo01** [comment]
Dat ligt aan Frank Energie. Er zijn geen gegevens beschikbaar.
Wel is er een aanpassing in de component nodig om hier beter mee om te gaan.

Op wo 2 nov. 2022 02:24 schreef tvdh91 ***@***.***>:

**Comment by bajansen** [comment]
Gefixt in b5a5781
