### ISSUE TITLE
Average price today wrong

### ISSUE THREAD

**Issue by HiDiHo01** [bajansen/home-assistant-frank_energie#32]
Gemiddelde prijs van vandaag klopt niet

<img src="https://i.gyazo.com/33c447c1ae8bdf84379c08b4726d83c3.png">

**Comment by bajansen** [comment]
Tot 02:00 wordt de data van de vorige dag nog meegenomen. Na dit tijdstip klopt het weer wel.
Ik heb ook het idee dat de site van Frank Energie op een iets andere manier ook last heeft van dit verschijnsel aangezien de gemiddelde stroomprijs nu weer 10 cent wordt aangegeven dan in je screenshot. Iets vergelijkbaars is me ook al eens opgevallen met gasprijzen die met terugwerkende kracht ineens lager/hoger bleken te zijn dan eerder aangegeven.
<img width="535" alt="Scherm­afbeelding 2022-11-04 om 09 08 50" src="https://user-images.githubusercontent.com/6934851/199923977-5aaa7c76-c799-47ed-ac96-a2c2d86898a0.png">

Uiteindelijk relateert dit weer aan #11. Ik sluit deze daarom en zal het binnenkort vanuit de bestaande issues en pull requests proberen op te pakken.

**Comment by HiDiHo01** [comment]
Daarom gooide ik dit "probleem" er weer in, issue staat al langer open en oplossing is om 2 uur van de volgende dag mee te nemen zoals mijn pull-request doet.
Daarnaast heb ik nog een vraag of je een beta kanaal wil openen waar pull request sneller aangenomen worden.
