### ISSUE TITLE
Retrying setup: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Bodmoor** [bajansen/home-assistant-frank_energie#33]
Hoi,

Ik heb geprobeerd de integratie opnieuw te installeren vandaag, omdat ik geen stroom en gasprijs meer zag staan in home assistant.

Ik krijgbde melding Retrying setup: 'NoneType' object is not subscriptable.

Gaat dit vanzelf over, als in komt dit door Frankenergie?

Mvg,
Paul

**Comment by HiDiHo01** [comment]
> Hoi,
> 
> Ik heb geprobeerd de integratie opnieuw te installeren vandaag, omdat ik geen stroom en gasprijs meer zag staan in home assistant.
> 
> Ik krijgbde melding Retrying setup: 'NoneType' object is not subscriptable.
> 
> Gaat dit vanzelf over, als in komt dit door Frankenergie?
> 
> Mvg, Paul

Ja dit komt door wijzigingen aan de API door Frank Energie en zou vanzelf goed moeten komen als ze het herstellen.
Wel raad ik aan de laatste versie van dit component te gebruiken om beter met fouten om te gaan.

**Comment by Bodmoor** [comment]
Ah klopt, na 15:00 uur werkte het weer. Maar om 01:00 weer niet, en om 15:00 de volgende dag weer wel. 

![Screenshot_20221105-090507](https://user-images.githubusercontent.com/18680317/200119290-49ba1845-9165-4c5c-b9ee-9f915babad5e.png)

**Comment by HiDiHo01** [comment]
Dit komt omdat om 0:00 uur de gegevens "op" zijn.
In de API zit een foutje in het ophalen bij zulu-tijd waardoor hij een uur van gister(in zomertijd 2 uur) probeert te laden die dan niet meer beschikbaar is.
De oplossing was om data van gister in te laden maar die data hebben ze verwijderd.

**Comment by Bodmoor** [comment]
Helder, dank voor de uitleg

**Comment by derSchreifritz** [comment]
wait, so does this mean it works only between 3pm and midnight or so? I have the same issue, and tried copy/paste the new code from 5 days ago, restart.. :  'NoneType' object is not subscriptable.
