### ISSUE TITLE
NextEnergy

### ISSUE THREAD

**Issue by joostvanmourik** [bajansen/home-assistant-frank_energie#34]
Zou het mogelijk zijn deze module ook te gebruiken voor NextEnergy

**Comment by HiDiHo01** [comment]
> Zou het mogelijk zijn deze module ook te gebruiken voor NextEnergy

In principe wel. Ze moeten dan wel een API aanbieden met prijzen en uurtarieven. Ik heb even **snel** gekeken en kan geen api vinden (https://www.programmableweb.com/category/energy/api)

Als ze dit wel hebben lijkt het mij beter daar gewoon een apart component voor te maken zoals bij iedere energie leverancier.

**Comment by bajansen** [comment]
Aangezien alle energieleveranciers die leveren op basis van day-ahead prijzen zich in principe op dezelfde data baseren zou je mogelijk een integratie kunnen bouwen die zich rechtstreeks op de beschikbare marktdata baseert en daar vervolgens de belastingen en vaste kosten van je betreffende leverancier bij op telt. Andersom zou je ook deze integratie kunnen gebruiken en zelf template-sensoren definiëren die de prijzen omrekenen naar het tarief van je eigen leverancier.

Deze integratie is in ieder geval specifiek gericht op Frank Energie en gebruikt data die bij Frank Energie wordt opgehaald. Op basis hiervan zullen we dus geen directe ondersteuning bieden voor andere leveranciers.
