### ISSUE TITLE
Request gas / elec option in config

### ISSUE THREAD

**Issue by HiDiHo01** [bajansen/home-assistant-frank_energie#35]
Is het mogelijk om een config flow te maken voor gas en elektra?
Dus bij setup en configuratie twee opties; gas / elektriciteit
Zelf kom ik er niet helemaal uit hoe dit werkt.

**Comment by corneyl** [comment]
@HiDiHo01 wat is daarvoor de use case? Wellicht wil je geen sensoren voor gas of elektriciteit? In dat geval: het is nu ook al mogelijk om bepaalde sensoren uit te schakelen (in de entiteitsinstellingen), dan worden ze ook niet weergegeven of bepaald.

**Comment by HiDiHo01** [comment]
> @HiDiHo01 wat is daarvoor de use case? Wellicht wil je geen sensoren voor gas of elektriciteit? In dat geval: het is nu ook al mogelijk om bepaalde sensoren uit te schakelen (in de entiteitsinstellingen), dan worden ze ook niet weergegeven of bepaald.

Ja je hebt gelijk. Ik zat af te kijken bij een ander component en dacht misschien is het handig.
<img src="https://i.gyazo.com/dc62a6a27288fcf328555d833a167b71.png">
