### ISSUE TITLE
Retrying setup: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ripburger** [bajansen/home-assistant-frank_energie#39]
Since last night, all the sensors show up as unavailable. The error that shows under Settings -> Integrations is Retrying setup: 'NoneType' object is not subscriptable.

Hope something can be done about this ? Thanks! :)

**Comment by edeba** [comment]
I have the same issue, hope you can help us. Regards, Eric

**Comment by berendhaan** [comment]
Frank has some issues no their side, the app isn't loading the current prices either.
