### ISSUE TITLE
Current prices for electricity and gas are incorrect?

### ISSUE THREAD

**Issue by loedeman** [bajansen/home-assistant-frank_energie#4]
While checking prices in HA compared to the Frank app, I tend to have prices different to the actual prices. AFAIK, the prices in HA are always 8 cents higher than in the app. Am I doing something wrong or am I misinterpreting data perhaps? For clarification, I added the prices between 8 AM and 8 PM today…

![7ACED875-6D10-477E-94CA-011E72D63619](https://user-images.githubusercontent.com/355132/155855138-249b3408-ff8a-40fa-b541-af2e99d3703f.png)

**Comment by loedeman** [comment]
Wow dat is een snelle reactie 😀. Bedankt voor de verduidelijking! Lekker duidelijk zijn ze bezig bij Frank 🤔. Ik zie de inkoop+ t.z.t. wel verschijnen!

Enne: superbedankt voor je werk aan de integratie! Mocht ik je es kunnen helpen, ik ben programmeur dus dan hoor ik het wel 😉…

**Comment by bajansen** [comment]
Inkoopprijs+ zit er nu in. Wanneer je ergens denkt te kunnen bijdragen, ga vooral je gang en maak een pull request. Als ik voor de helft weet wat ik hier aan het doen ben is het veel.

**Comment by loedeman** [comment]
Haha, voor de helft ook 😀.
