### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by joostvanmourik** [bajansen/home-assistant-frank_energie#40]
On the last version i get an error:

Opnieuw proberen in te stellen: 'NoneType' object is not subscriptable

**Comment by HiDiHo01** [comment]
API was not available. It's back now.
Update to last release for better error handling.

**Comment by edeba** [comment]
I still got an error; 

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.frank_energie.coordinator
Source: custom_components/frank_energie/coordinator.py:48 
Integration: Frank Energie (documentation, issues) 
First occurred: 11:28:58 (74 occurrences) 
Last logged: 13:01:34

Unexpected error fetching Frank Energie coordinator data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/frank_energie/coordinator.py", line 48, in _async_update_data
    'marketPricesElectricity': data_today['marketPricesElectricity'] + data_tomorrow['marketPricesElectricity'],
TypeError: 'NoneType' object is not subscriptable

**Comment by edeba** [comment]
It is working again, thanks for the fast response!

**Comment by dickydick666** [comment]
Ik moet zeggen dat ik net begonnen ben met home assistant dus het kan zijn dat ik dingen gewoon verkeerd configureer, maar ik wil dit toch even vermelden om er zeker van te zijn dat ik niet in de verkeerde richting aan het zoeken ben.
Na het toevoegen van de Frank integraties worden de tarieven opgehaald en daarna niet meer. Pas wanneer ik home assistant herstart / reboot worden de tarieven opnieuw ingelezen, is dit een bug of iets anders?

**Comment by glijie** [comment]
ligt niet aan jou,  sinds volgens mij gisteren precies hetzelfde euvel. Tarieven worden niet opnieuw ingelezen bij verandering.

**Comment by joostvanmourik** [comment]
Yup ik heb het hier ook

**Comment by corneyl** [comment]
@edeba Het probleem met de `TypeError` is inderdaad opgelost in de laatste versie. Het probleem dat tarieven niet altijd worden opgehaald kan verder worden besproken in issue #44.
