### ISSUE TITLE
Prijzen lijken niet opgehaald te worden.

### ISSUE THREAD

**Issue by dickydick666** [bajansen/home-assistant-frank_energie#44]
Ik moet zeggen dat ik net begonnen ben met home assistant dus het kan zijn dat ik dingen gewoon verkeerd configureer, maar ik wil dit toch even vermelden om er zeker van te zijn dat ik niet in de verkeerde richting aan het zoeken ben.
Na het toevoegen van de Frank integraties worden de tarieven opgehaald en daarna niet meer. Pas wanneer ik home assistant herstart / reboot worden de tarieven opnieuw ingelezen, is dit een bug of iets anders?

**Comment by joostvanmourik** [comment]
Klopt sinds gisteren heb ik dit ook

**Comment by dickydick666** [comment]
Oke, gelukkig, dank je wel. Dan wacht ik op rustig een update

**Comment by corneyl** [comment]
Zijn er nog specifieke errors in de HA logging die zouden kunnen aanduiden wat het probleem is?

**Comment by dickydick666** [comment]
![afbeelding](https://user-images.githubusercontent.com/117838472/201118020-c076f7b3-6165-478c-97be-773fc509187a.png)

**Comment by dickydick666** [comment]
Niets bijzonder lijkt mij.

**Comment by JIK12345** [comment]
Hier ook hetzelfde probleem. Prijzen veranderen alleen als ik de service reload, niet meer elk uur (voor stroom).
