### ISSUE TITLE
no price per hour for the day?

### ISSUE THREAD

**Issue by MathiasEveraerts** [bajansen/home-assistant-frank_energie#46]
Is it possible to have the price per hour so you can automate more? do manual stuff?

**Comment by JohnMoor** [comment]
I was wondering the same after trying this integration today. Looking through the [issue list](https://github.com/bajansen/home-assistant-frank_energie/issues/2#issuecomment-1062007438) I see @bajansen did add this to the future_pricing branch. Not sure though if it made it to the main branch.

**Comment by corneyl** [comment]
@MathiasEveraerts @JohnMoor I've created a PR which adds the price per hour as attribute to a few sensors. If you want you can test it with that code.
