### ISSUE TITLE
Feature request: Implement future prices

### ISSUE THREAD

**Issue by cascer1** [bajansen/home-assistant-frank_energie#5]
Hi!

I believe the Frank API is able to return tomorrow's prices as well as the current price. Would it be possible to somehow add these to the integration? I'd love to be able to see the prices in a graph so that I can better decide when to turn on certain appliances.

Thanks

**Comment by bajansen** [comment]
Dit is min of meer hetzelfde als issue #2. Ik heb een tijd terug een probeersel in die richting gebouwd maar het schort nog even op het gebied van afronding. Ik zal later vandaag de boel even naar een nieuwe branch duwen zodat er wellicht wat meegedacht en -getest kan worden.
