### ISSUE TITLE
No sensors visible after install with HACS

### ISSUE THREAD

**Issue by chvos** [bajansen/home-assistant-frank_energie#50]
Hi, 

Maybe I'm doing something wrong, but I downloaded the component via the HACS custom integration, it's in the custom_components folder, restarted home assistant but the sensors do not show when I search them in entities. I have some sensors set up in my config file, but nothing for this custom component could this cause a problem?

Maybe I'm missing something?

**Comment by corneyl** [comment]
The setup is not done in your config file, but on the integrations settings page you can add the integration to set it up. See also the readme.

**Comment by chvos** [comment]
Yes I followed the readme by adding it via HACS. I never used this custom component before, so I did not add anything to my configuration.yaml. The frank_energie folder is visible in my custom_components folder but no sensors show after reboot. I don’t see errors in the log for the frank_energie component. 

![2BED0DC8-14BD-42BC-86AA-5CD835816084](https://user-images.githubusercontent.com/46753935/203912955-45fd40a4-d93a-435d-b0bc-623d0725da35.png)
![1CB164F6-BB3A-4C5B-AA69-0406929D2F3C](https://user-images.githubusercontent.com/46753935/203912968-1a4e06d1-8405-4c06-bc1f-a6a18143bddb.png)

**Comment by corneyl** [comment]
Ik doelde specifiek op het 'configuratie' deel van de readme 😃, zie https://github.com/bajansen/home-assistant-frank_energie#configuratie.

Dus bij 'Instellingen' -> 'Apparaten en Diensten' kun je op '+ Integratie toevoegen' klikken en dan 'Frank Energie' kiezen. Dan komen de sensors beschikbaar.

**Comment by chvos** [comment]
Hi Corneyl,

Dankjewel, beetje knullig overheen gekeken. Het werkt inmiddels!
