### ISSUE TITLE
Apex card example does not load data

### ISSUE THREAD

**Issue by Ferrox85** [bajansen/home-assistant-frank_energie#52]
The example does not load any data. It shows only the label "nu", it keeps loading till eternity.

Some help would be appreciated. Not sure why this is happening.

**Comment by bajansen** [comment]
Are you using the latest version of the integration? The functionality of the Aphex card depends on the upcoming pricing information being available as an attribute to the `current_electricity_price_all_in` sensor which was added in version 1.2.0.
