### ISSUE TITLE
Error setting up entry Frank Energie for frank_energie

### ISSUE THREAD

**Issue by JTeijema** [bajansen/home-assistant-frank_energie#64]
Deze fout is ontstaan door een aangepaste integratie.

```Console
Logger: homeassistant.config_entries
Source: custom_components/frank_energie/__init__.py:32
Integration: Frank Energie (documentation, issues)
First occurred: 21:46:21 (3 occurrences)
Last logged: 23:48:14

Error setting up entry Frank Energie for frank_energie
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/frank_energie/__init__.py", line 32, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setups'
```

Error wordt direct gegeven na integratie succes melding. Integratie werkt niet.

Op versie: Home Assistant 2022.3.0b4

**Comment by JTeijema** [comment]
#65 Fixes this issue for me, but this might not be universal. 
![afbeelding](https://user-images.githubusercontent.com/28191416/224515560-1bb52cb3-615a-4fa3-9e67-e777bc4d1bc6.png)

**Comment by DCSBL** [comment]
The original method should just work, many integrations are using it without issues. Maybe something else went wrong before that call?

Also, as you mention a (very old) beta release. Have you tried this with 2023.3?

**Comment by JTeijema** [comment]
New version seems to work. Old version seems to be the problem.
