### ISSUE TITLE
All-in prijsinformatie onjuist

### ISSUE THREAD

**Issue by bajansen** [bajansen/home-assistant-frank_energie#7]
Sinds vanavond (2022-03-30) 20:00 lijkt Frank Energie een aanpassing te hebben doorgevoerd in de prijsinformatie. Wat voorheen de 'all-in' prijs was lijkt nu gelijk te zijn aan 'inkoopprijs+', zoals in de app en op hun website. Frank Energie heeft in een mailing aangegeven dat de all-in prijs binnenkort weer in app en op hun website beschikbaar wordt gemaakt. Wanneer dit het geval is moet het nieuwe veld met de all-in waarde te achterhalen zijn.

<img width="380" alt="Schermafbeelding 2022-03-30 om 22 46 22" src="https://user-images.githubusercontent.com/6934851/160927930-86975558-b97f-4ff6-8a39-6bfe17d6196c.png">

**Comment by mcormick** [comment]
Volgens [de overheid](https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/overige_belastingen/belastingen_op_milieugrondslag/tarieven_milieubelastingen/tabellen_tarieven_milieubelastingen) zijn de belastingen (ex btw) voor 2022 als volgt:

Gas per m³: 
ODE 0.10467
Energiebelasting: 0.36322
Frank inkoopvergoeding: 0.0967

Electricity per Kwh:
ODE: 0.0305
Energiebelasting: 0.03679
Frank inkoopvergoeding: 0.0169

All-in prijs zou in de tussentijd berekend kunnen worden door:
(Inkooptarief + ODE + energiebelasting + inkoopvergoeding) * 1.21

**Comment by Yveaux** [comment]
Het 'priceIncludingMarkup' veld dat deze home-assistant plugin gebruikt is als 'deprecated' gemarkeerd in het Graphql schema, en kan dus beter niet meer gebruikt worden.

De volgende velden zijn beschikbaar in de API (identiek voor electra & gas):

```
## Electra (verandert per uur)
curl -g -X POST -H "Content-Type: application/json" -d '{"query":"query MarketPrices { marketPricesElectricity(startDate: \"'2022-04-01'\" endDate: \"'2022-04-02'\") { till from marketPrice marketPriceTax sourcingMarkupPrice energyTaxPrice priceMarkup priceIncludingMarkup } }"}' https://frank-api.nl/graphql

{
   "data":{
      "marketPricesElectricity":[
         {
            "till":"2022-04-01T00:00:00.000Z",
            "from":"2022-03-31T23:00:00.000Z",
            "marketPrice":0.1733,
            "marketPriceTax":0.0363846,
            "sourcingMarkupPrice":0.0169,
            "energyTaxPrice":0.0814,
            "priceMarkup":0.0169,               // deprecated
            "priceIncludingMarkup":0.2266       // deprecated
         },
        /* Etc */
      ]
   }
}
```


```
## Gas (verandert 2x per dag)
curl -g -X POST -H "Content-Type: application/json" -d '{"query":"query MarketPrices { marketPricesGas(startDate: \"'2022-04-01'\" endDate: \"'2022-04-02'\") { till from marketPrice marketPriceTax sourcingMarkupPrice energyTaxPrice priceMarkup priceIncludingMarkup } }"}' https://frank-api.nl/graphql

{
   "data":{
      "marketPricesGas":[
         {
            "till":"2022-04-01T00:00:00.000Z",
            "from":"2022-03-31T23:00:00.000Z",
            "marketPrice":1.1376,
            "marketPriceTax":0.2389,
            "sourcingMarkupPrice":0.0968,
            "energyTaxPrice":0.5442,
            "priceMarkup":0.0968,               // deprecated
            "priceIncludingMarkup":1.4733       // deprecated
         },
        /* Etc */
       ]
   }
}
```

Prijzen worden als volgt opgebouwd/getoond op de frank website/app:

- Inkoopprijs (ex BTW) =    marketPrice
- Inkoopprijs+ (incl BTW) = marketPrice + marketPriceTax + sourcingMarkupPrice
- Verkoopprijs (incl BTW) = marketPrice + marketPriceTax + sourcingMarkupPrice + energyTaxPrice

Wij betalen uiteindelijk de verkoopprijs. Deze wordt nu niet op de website/app getoond, maar Frank heeft aangekondigd deze binnenkort wel te gaan tonen.

@bajansen het lijkt me een kleine change om deze opbouw te ondersteunen in de plugin. Zie ook dat je een andere API ingang gebruikt; kun je uitleggen waarom?

**Comment by bajansen** [comment]
@Yveaux, bedankt voor het uitpluizen van de graphqlstructuren. Ik heb zojuist een update gepusht die de all-in prijs uitrekent met de beschikbare waarden.

Het API endpoint dat ik gebruik heb ik achterhaald via de website van Frank Energie. Zij gebruiken dit endpoint ook nog steeds voor de prijsinformatie. Mag ik vragen waar je het door jou gebruikte endpoint hebt opgesnord?

**Comment by Yveaux** [comment]
@bajansen ik heb het endpoint hier gevonden: https://community.home-assistant.io/t/rest-sensor-with-yesterdays-and-todays-date-in-the-payload/352791

**Comment by bajansen** [comment]
Aangezien het huidige endpoint ook door Frank Energie zelf wordt gebruikt houd ik hier voorlopig maar aan vast.
De all-in prijs is sinds bc8b4810300da50179dbc023a9c823f64e4e1004 weer beschikbaar in de integratie. Mocht Frank Energie weer eens een hapklare all-in prijs in hun grahpql data zetten dan zien we dat dan wel weer.
