### ISSUE TITLE
user-error:auth-not-authorised

### ISSUE THREAD

**Issue by HiDiHo01** [bajansen/home-assistant-frank_energie#83]
I have to login again after some time.
Do more people have this?

**Comment by DCSBL** [comment]
Yeah, we have to implement the renewToken API in the upstream library to do this automaticly for us. I had not time to fix this, so thank you for opening this issue.

https://github.com/DCSBL/python-frank-energie/blob/228cc919332077d6cf36e4666069bfc7a4d86c21/python_frank_energie/frank_energie.py#L71-L84

We should call this API with the stored renewToken and refreshToken to do this, and update the returned values in HA. 

You can pick that up if you want? For the coming weeks I won't work in this.. 🎮 

_I also see that we have to clean up some debugging stuff_

**Comment by DCSBL** [comment]
I think we can tackle this one with [python-frank-energie:5.0.0](https://github.com/DCSBL/python-frank-energie/releases/tag/5.0.0), can you try this @HiDiHo01 ?

**Comment by HiDiHo01** [comment]
Thanks for your comments and update, I will test version 5.

**Comment by DCSBL** [comment]
Closed with #84
