### ISSUE TITLE
Password is cleared, every n days

### ISSUE THREAD

**Issue by Eigeman** [bajansen/home-assistant-frank_energie#91]
Integration works fine, but every few days (less than a month) the password is lost, and has to be set again.
This does not seem to be related to installing updates, but happens randomly, for example last night (1 to 2 september)

**Comment by DCSBL** [comment]
This should have been fixed with the latest update ([v2.5.0](https://github.com/bajansen/home-assistant-frank_energie/releases/tag/v2.5.0))

Do you have this version installed? If so, can you please see if you have any logs or other indicators that can help to resolve this?

**Comment by Eigeman** [comment]
Thanks. I've installed the new version. I will close this one and reopen when it occurs again.
