### ISSUE TITLE
No prices anymore

### ISSUE THREAD

**Issue by HiDiHo01** [bajansen/home-assistant-frank_energie#95]
No prices for tomorrow anymore?
There are also no prices on Frank site and app.

**Comment by HiDiHo01** [comment]
And now no prices at all anymore
I hope they fix it soon

<img src="https://i.gyazo.com/ed37c8be1b1d51934b5bd0deaa0d9206.png">

**Comment by pggm-thijs** [comment]
Same here!

**Comment by bajansen** [comment]
Aangezien de prijsinformatiewidget van Frank Energie zelf ook geen data laat zien is dit een probleem aan hun zijde en niet een gewijzigd API-endpoint of iets dergelijks. Dit is dus niet iets wat we in de integratie kunnen oplossen, maar ik laat het issue wel even open staan ter informatie voor anderen.

**Comment by pggm-thijs** [comment]
Dank, ik heb contact gehad met Frank. Ze erkennen de storing en geven aan te werken aan de oplossing.
